#ifndef LTE_TYPES_H
#define LTE_TYPES_H

#include <stdint.h>

/** @brief Enumeration of LTE event types. 
 * 
 * @note This enumeration defines the types of events that can be generated by the LTE modem.
 * It is used in the event queue to manage communication with the modem.    
 * 
 * @note The event types include:
 * - LTE_EVENT_NONE: No event           
 * - LTE_EVENT_RX_LINE: A new line has been received from the modem 
 * - LTE_EVENT_TIMEOUT: A timeout has occurred  
 * - LTE_EVENT_ERROR: An error has occurred
 */

typedef enum {
    LTE_EVENT_NONE = 0,
    LTE_EVENT_RX_LINE,
    LTE_EVENT_TIMEOUT,
    LTE_EVENT_ERROR
} LteEventType_t;


/**
 * @brief Structure representing an event from the LTE modem.   
 * 
 * @note This structure is used to encapsulate events such as received lines, 
 * timeouts, and errors from the LTE modem. It is used in the event queue to manage
 *  communication with the modem.    
 * 
 * @note The `line` field is only valid for `LTE_EVENT_RX_LINE` events. For other event types, it may be NULL.  
 * 
 */
typedef struct {
    LteEventType_t type;
    const char    *line; 
} LteEvent_t;

/** 
 * @brief Enumeration of LTE state machine states.  
 *  
 * @note This enumeration defines the various states of the LTE state machine, 
 * which manages the modem's operation.  Each state corresponds to a specific phase in the modem's lifecycle, 
 * from initialization to running and error handling.     
 *  
 * @note The state machine transitions between these states based on events 
 * received from the modem and the success or failure of AT commands.  
 * 
 * 
 */

typedef enum {
    LTE_SM_IDLE = 0,
    LTE_SM_INIT,
    LTE_SM_POWER_ON,
    LTE_SM_WAIT_BOOT,
    LTE_SM_CHECK_SIM,
    LTE_SM_ATTACH,
    LTE_SM_PDP,
    LTE_SM_OPEN_SOCKET,
    LTE_SM_MQTT_CONNECT,
    LTE_SM_MQTT_SUBSCRIBE,
    LTE_SM_RUN,
    REATTACH,
    REPDP,
    REOPEN_SOCKET,
    MQTT_RECONNECT,
    MQTT_RESUBSCRIBE,
    REBOOT_MODEM,
    LTE_SM_ERROR,
    LET_SM_INVALID
} LteSmState_t;

#endif /* LTE_TYPES_H */
